export const HOME_PAGE = '/'
export const ADD_WORK_PAGE = '/add-work'
export const ADD_PAPER_PAGE = '/add-paper'
export const ADD_REPORT_PAGE = '/add-report'
export const ADD_SERVICE_PAGE = '/add-service'
export const ADD_ADVANTAGES_MAIN = '/add-advantages-main'

export const WORKS_PAGE = '/show-works'
export const PAPERS_PAGE = '/show-papers'
export const REPORTS_PAGE = '/show-reports'
export const SERVICES_PAGE = '/show-services'
export const PAGE_BANNERS = '/page-banners/'

export const PAGE_LOGIN = '/login'
export const EDIT_PAGE = '/edit-page/'
export const EDIT_MAIN_PAGE = '/edit-main-page/'
