export const HOME_PAGE = '/'
export const HOME_DOCUMENT = '/doc/'

export const ADD_WORK_PAGE = '/add-work/'
export const ADD_PAPER_PAGE = '/add-paper/'
export const ADD_REPORT_PAGE = '/add-report/'
export const ADD_SERVICE_PAGE = '/add-service/'
export const ADD_ADVANTAGES_MAIN = '/add-advantages-main/'
export const ADD_MAIN_PAGE_CARD = '/add-main-page-card/'
export const ADD_SLIDE = '/add-slide/'

export const ADD_STATION_PHOTOS = '/add-station-photos/'
export const WORKS_PAGE = '/show-works'
export const PAPERS_PAGE = '/show-papers'
export const REPORTS_PAGE = '/show-reports/'
export const SERVICES_PAGE = '/show-services'
export const PAGE_BANNERS = '/page-banners/'
export const PAGE_SLIDE = '/slide/'

export const PAGE_LOGIN = '/login'
export const PAGE_CONTACTS = '/contacts'
export const EDIT_PAGE = '/edit-page/'
export const EDIT_MAIN_PAGE = '/edit-main-page/'

export const NEW_ITEM = 'new-item'
